#language: pt

@ALL @CONFIGURACOES_TIPO_PAGAMENTO
Funcionalidade: Validar os direitos na tela Configuracoes > Tipo de pagamentos

Contexto:
Dado que eu faca login

@CONFIGURACOES_PRECO_VER
@CADASTRO_ANALISTA_CIELO @CADASTRO_ANALISTA_CIELO_APROVADOR @CENTRAL_HELP_DESK_ANALISTA
@LOGISTICA_DE_ATENDIMENTO_A_CLIENTES_ANALISTA @PLANEJA_BACKOFFICE_COBRAN_FATURA_ANALISTA @CHARGEBACK_ANALISTA_INTERCAMBIO
@CENTRAL_DE_RELACIONAMENTO_ANALISTA @CENTRAL_ANTECIPACAO_COORDENADOR @CENTRAL_ANTECIPACAO_ANALISTA
@GESTAO_ECONOMICA_ANALISTA @CRM_COORDENADOR @ANTECIPACAO_DE_VENDAS_TESOURARIA_ANALISTA
@ANTECIPACAO_DE_VENDAS_TESOURARIA_COORDENADOR
Cenario: Validar direito CONFIGURACOES_PRECO_VER
Dado que tenha/nao tenha o direito "CONFIGURACOES_PRECO_VER"
E que tenha/nao tenha acesso na tela "Preço padrão"
Entao o sistema exibira/nao exibira a tela "Preço padrão"

@CONFIGURACOES_PRECO_EDITAR
Cenario: Validar direito CONFIGURACOES_PRECO_EDITAR
Dado que tenha/nao tenha o direito "CONFIGURACOES_PRECO_EDITAR"
E que tenha/nao tenha acesso na tela "Preço padrão"
Quando clicar na aba "ATUALIZAR"
Entao podera/nao podera acessar a aba "ATUALIZAR"

@CONFIGURACOES_TIPODEPAGAMENTO_VER
@RELACIONAMENTO_SUPORTE_COMERCIAL_ANALISTA @CADASTRO_ANALISTA_CIELO @CADASTRO_ANALISTA_CIELO_APROVADOR
@CENTRAL_HELP_DESK_ANALISTA @LOGISTICA_DE_ATENDIMENTO_A_CLIENTES_ANALISTA @BACKOFFICE_ANALISTA_FORNECEDOR
@PLANEJA_BACKOFFICE_COBRAN_FATURA_ANALISTA @CHARGEBACK_ANALISTA_INTERCAMBIO
@CENTRAL_DE_RELACIONAMENTO_ANALISTA @CENTRAL_ANTECIPACAO_COORDENADOR @CENTRAL_ANTECIPACAO_ANALISTA
@GESTAO_ECONOMICA_ANALISTA @JURIDICO_CONTENCIOSO_ANALISTA @CRM_COORDENADOR
@ANTECIPACAO_DE_VENDAS_TESOURARIA_ANALISTA @ANTECIPACAO_DE_VENDAS_TESOURARIA_COORDENADOR
Cenario: Validar direito CONFIGURACOES_TIPODEPAGAMENTO_VER
Dado que tenha/nao tenha o direito "CONFIGURACOES_TIPODEPAGAMENTO_VER"
E que tenha/nao tenha acesso na tela "Pesquisa"
Entao o sistema exibira/nao exibira a tela "Tipo de pagamento"

@CONFIGURACOES_TIPODEPAGAMENTO_EDITAR
Cenario: Validar direito CONFIGURACOES_TIPODEPAGAMENTO_EDITAR
Dado que tenha/nao tenha o direito "CONFIGURACOES_TIPODEPAGAMENTO_EDITAR"
E que tenha/nao tenha acesso na tela "Pesquisa"
Quando clicar no botao "Pesquisar"
E clicar na acao "Visualizar"
Entao o botao "Editar" devera estar habilitado/desabilitado
