#language: pt

@ALL @CONFIGURACOES_ANTECIPACAOVENDAS
Funcionalidade: Validar os direitos na tela Configurações > Antecipação de vendas

Contexto:
Dado que eu faca login

@CONFIGURACOES_ANTECIPACAOVENDAS_PRECIFICACAO_CONSULTAGERAL_VER
@RELACIONAMENTO_SUPORTE_COMERCIAL_ANALISTA @TESOURARIA_E_CONTAS_A_PAGAR_ANALISTA @TESOURARIA_ANALISTA
@GESTAO_ECONOMICA_ANALISTA @CANAIS_ALTERNATIVOS_ANALISTA @CONTABILIDADE_NEGOCIO_E_TRIBUTARIO_ANALISTA
@JURIDICO_CONTENCIOSO_ANALISTA
Cenario: CT.SEGINFO - [AUT] CONFIGURACOES_ANTECIPACAOVENDAS_PRECIFICACAO_CONSULTAGERAL_VER
Dado que tenha/nao tenha o direito "CONFIGURACOES_ANTECIPACAOVENDAS_PRECIFICACAO_CONSULTAGERAL_VER"
E que tenha/nao tenha acesso na tela "Precificação_antecipaçãoVendas"
# E que tenha/nao tenha acesso na tela "Consulta geral"
Entao o sistema exibira/nao exibira a tela "Precificação", "1"

@CONFIGURACOES_ANTECIPACAOVENDAS_PRECIFICACAO_CONSULTAPORCANAL_VER
@RELACIONAMENTO_SUPORTE_COMERCIAL_ANALISTA @PLANEJA_BACKOFFICE_COBRAN_FATURA_ANALISTA @TESOURARIA_E_CONTAS_A_PAGAR_ANALISTA
@CENTRAL_DE_RELACIONAMENTO_ANALISTA @TESOURARIA_ANALISTA @CENTRAL_ANTECIPACAO_COORDENADOR
@GESTAO_ECONOMICA_ANALISTA @CANAIS_ALTERNATIVOS_ANALISTA @CONTABILIDADE_NEGOCIO_E_TRIBUTARIO_ANALISTA
@CRM_COORDENADOR
Cenario: CT.SEGINFO - [AUT] CONFIGURACOES_ANTECIPACAOVENDAS_PRECIFICACAO_CONSULTAPORCANAL_VER
Dado que tenha/nao tenha o direito "CONFIGURACOES_ANTECIPACAOVENDAS_PRECIFICACAO_CONSULTAPORCANAL_VER"
E que tenha/nao tenha acesso na tela "Precificação_antecipaçãoVendas"
E clicar na aba "Preço por canal", "1"


@CONFIGURACOES_ANTECIPACAOVENDAS_CONFIGURACOESGERAIS_TAXAEFETIVAMAXIMA_VER
Cenario: CT.SEGINFO - [AUT] CONFIGURACOES_ANTECIPACAOVENDAS_CONFIGURACOESGERAIS_TAXAEFETIVAMAXIMA_VER
Dado que tenha/nao tenha o direito "CONFIGURACOES_ANTECIPACAOVENDAS_CONFIGURACOESGERAIS_TAXAEFETIVAMAXIMA_VER"
E que tenha/nao tenha acesso na tela "Geral_antecipaçãoVendas"
Entao localizar o frame "Taxa efetiva máxima", "1"

@CONFIGURACOES_ANTECIPACAOVENDAS_CONFIGURACOES_RESERVAFINANCEIRA_VER
@RELACIONAMENTO_SUPORTE_COMERCIAL_ANALISTA @PLANEJA_BACKOFFICE_COBRAN_FATURA_ANALISTA
@CHARGEBACK_ANALISTA_INTERCAMBIO @CENTRAL_DE_RELACIONAMENTO_ANALISTA
@CENTRAL_ANTECIPACAO_COORDENADOR @CENTRAL_ANTECIPACAO_ANALISTA @GESTAO_ECONOMICA_ANALISTA
@CANAIS_ALTERNATIVOS_ANALISTA @CRM_COORDENADOR @ANTECIPACAO_DE_VENDAS_TESOURARIA_ANALISTA
@ANTECIPACAO_DE_VENDAS_TESOURARIA_COORDENADOR
Cenario: CT.SEGINFO - [AUT] CONFIGURACOES_ANTECIPACAOVENDAS_CONFIGURACOES_RESERVAFINANCEIRA_VER
Dado que tenha/nao tenha o direito "CONFIGURACOES_ANTECIPACAOVENDAS_CONFIGURACOES_RESERVAFINANCEIRA_VER"
E que tenha/nao tenha acesso na tela "Geral_antecipaçãoVendas"
Entao localizar o frame "Reserva financeira", "1"

@CONFIGURACOES_ANTECIPACAOVENDAS_EXCECAO_CARTAONAOPRESENTE_VER
Cenario: CT.SEGINFO - [AUT] CONFIGURACOES_ANTECIPACAOVENDAS_EXCECAO_CARTAONAOPRESENTE_VER
Dado que tenha/nao tenha o direito "CONFIGURACOES_ANTECIPACAOVENDAS_EXCECAO_CARTAONAOPRESENTE_VER"
E que tenha/nao tenha acesso na tela "Exceção_antecipaçãoVendas"
Entao o sistema exibira/nao exibira a tela "Exceção", "0"
E clicar na aba "Cartão não presente", "0"
Entao o botao "Pesquisar", "1" estara habilitado/desabilitado


@CONFIGURACOES_ANTECIPACAOVENDAS_PRECIFICACAO_CONSULTAPORCANAL_EDITAR
Cenario: CT.SEGINFO - [AUT] CONFIGURACOES_ANTECIPACAOVENDAS_PRECIFICACAO_CONSULTAPORCANAL_EDITAR
Dado que tenha/nao tenha o direito "CONFIGURACOES_ANTECIPACAOVENDAS_PRECIFICACAO_CONSULTAPORCANAL_EDITAR"
E que tenha/nao tenha acesso na tela "Precificação_antecipaçãoVendas"
Quando clicar no botao "Editar", "0"
Entao o sistema exibira/nao exibira a tela "Precificação", "1"

@CONFIGURACOES_ANTECIPACAOVENDAS_CONFIGURACOESGERAIS_TAXAEFETIVAMAXIMA_EDITAR
Cenario: CT.SEGINFO - [AUT] CONFIGURACOES_ANTECIPACAOVENDAS_CONFIGURACOESGERAIS_TAXAEFETIVAMAXIMA_EDITAR
Dado que tenha/nao tenha o direito "CONFIGURACOES_ANTECIPACAOVENDAS_CONFIGURACOESGERAIS_TAXAEFETIVAMAXIMA_EDITAR"
E que tenha/nao tenha acesso na tela "Geral_antecipaçãoVendas"
Entao clicar no botao "Editar dados" do frame "taxa efetiva máxima", "1"

@CONFIGURACOES_ANTECIPACAOVENDAS_CONFIGURACOES_RESERVAFINANCEIRA_EDITAR
@ANTECIPACAO_DE_VENDAS_TESOURARIA_ANALISTA @ANTECIPACAO_DE_VENDAS_TESOURARIA_COORDENADOR
Cenario: CT.SEGINFO - [AUT] CONFIGURACOES_ANTECIPACAOVENDAS_CONFIGURACOES_RESERVAFINANCEIRA_EDITAR
Dado que tenha/nao tenha o direito "CONFIGURACOES_ANTECIPACAOVENDAS_CONFIGURACOES_RESERVAFINANCEIRA_EDITAR"
E que tenha/nao tenha acesso na tela "Geral_antecipaçãoVendas"
Entao clicar no botao "Editar dados" do frame "Reserva financeira", "1"

@CONFIGURACOES_ANTECIPACAOVENDAS_PRECIFICACAO_PRECOESPECIAL_EDITAR
Cenario: CT.SEGINFO - [AUT] CONFIGURACOES_ANTECIPACAOVENDAS_PRECIFICACAO_PRECOESPECIAL_EDITAR
Dado que tenha/nao tenha o direito "CONFIGURACOES_ANTECIPACAOVENDAS_PRECIFICACAO_PRECOESPECIAL_EDITAR"
E que tenha/nao tenha acesso na tela "Precificação_antecipaçãoVendas"
Quando clicar na aba "Preço Especial", "0"
E clicar na aba "Incluir", "0"
Entao o sistema exibira/nao exibira a tela "Precificação", "1"

@CONFIGURACOES_ANTECIPACAOVENDAS_PRECIFICACAO_PRECOESPECIAL_VER
Cenario: CT.SEGINFO - [AUT] CONFIGURACOES_ANTECIPACAOVENDAS_PRECIFICACAO_PRECOESPECIAL_VER
Dado que tenha/nao tenha o direito "CONFIGURACOES_ANTECIPACAOVENDAS_PRECIFICACAO_PRECOESPECIAL_VER"
E que tenha/nao tenha acesso na tela "Precificação_antecipaçãoVendas"
Quando clicar na aba "Preço Especial", "0"
Entao podera/nao podera acessar a aba "Preço Especial"

@SETUP_ARVCONFIGURACOES_GERAIS_ATRIBUICAOCATEGORIAPRECO_EDITAR
Cenario: CT.SEGINFO - [AUT] SETUP_ARVCONFIGURACOES_GERAIS_ATRIBUICAOCATEGORIAPRECO_EDITAR
Dado que tenha/nao tenha o direito "SETUP_ARVCONFIGURACOES_GERAIS_ATRIBUICAOCATEGORIAPRECO_EDITAR"
E que tenha/nao tenha acesso na tela "Geral_antecipaçãoVendas"
Entao clicar no botao "Editar dados" do frame "Atribuição de categoria/preço", "1"

@SETUP_ARV_CUSTOS_CUSTO_OPERACIONAL_VER
@GESTAO_ECONOMICA_ANALISTA @ANTECIPACAO_DE_VENDAS_TESOURARIA_ANALISTA
@ANTECIPACAO_DE_VENDAS_TESOURARIA_COORDENADOR
Cenario: CT.SEGINFO - [AUT] SETUP_ARV_CUSTOS_CUSTO_OPERACIONAL_VER
Dado que tenha/nao tenha o direito "SETUP_ARV_CUSTOS_CUSTO_OPERACIONAL_VER"
E que tenha/nao tenha acesso na tela "Custos"
Entao clicar na aba "CUSTO OPERACIONAL", "1"

@SETUP_ARV_CUSTOS_CDI_VER
@CENTRAL_DE_RELACIONAMENTO_ANALISTA @CENTRAL_ANTECIPACAO_COORDENADOR @CENTRAL_ANTECIPACAO_ANALISTA
@GESTAO_ECONOMICA_ANALISTA @CRM_COORDENADOR @ANTECIPACAO_DE_VENDAS_TESOURARIA_ANALISTA
@ANTECIPACAO_DE_VENDAS_TESOURARIA_COORDENADOR
Cenario: CT.SEGINFO - [AUT] SETUP_ARV_CUSTOS_CDI_VER
Dado que tenha/nao tenha o direito "SETUP_ARV_CUSTOS_CDI_VER"
E que tenha/nao tenha acesso na tela "Custos"
Entao clicar na aba "CDI", "1"

@SETUP_ARV_CUSTOS_CUSTO_CAPTACAO_VER
@GESTAO_ECONOMICA_ANALISTA @ANTECIPACAO_DE_VENDAS_TESOURARIA_ANALISTA
@ANTECIPACAO_DE_VENDAS_TESOURARIA_COORDENADOR
Cenario: CT.SEGINFO - [AUT] SETUP_ARV_CUSTOS_CUSTO_CAPTACAO_VER
Dado que tenha/nao tenha o direito "SETUP_ARV_CUSTOS_CUSTO_CAPTACAO_VER"
E que tenha/nao tenha acesso na tela "Custos"
Entao clicar na aba "CUSTO DE CAPTAÇÃO", "1"

@SETUP_ARVCONFIGURACOES_GERAIS_ATRIBUICAOCATEGORIAPRECO_VER
@RELACIONAMENTO_SUPORTE_COMERCIAL_ANALISTA @CENTRAL_DE_RELACIONAMENTO_ANALISTA @CENTRAL_ANTECIPACAO_COORDENADOR
@CENTRAL_ANTECIPACAO_ANALISTA @GESTAO_ECONOMICA_ANALISTA @CANAIS_ALTERNATIVOS_ANALISTA
@CRM_COORDENADOR
Cenario: CT.SEGINFO - [AUT] SETUP_ARVCONFIGURACOES_GERAIS_ATRIBUICAOCATEGORIAPRECO_VER
Dado que tenha/nao tenha o direito "SETUP_ARVCONFIGURACOES_GERAIS_ATRIBUICAOCATEGORIAPRECO_VER"
E que tenha/nao tenha acesso na tela "Geral_antecipaçãoVendas"
Entao localizar o frame "Atribuição de categoria/preço", "1"

@SETUP_ARVCONFIGURACOES_GERAIS_RAMOSDEATIVIDADERESTRITOS_EDITAR
Cenario: CT.SEGINFO - [AUT] SETUP_ARVCONFIGURACOES_GERAIS_RAMOSDEATIVIDADERESTRITOS_EDITAR
Dado que tenha/nao tenha o direito "SETUP_ARVCONFIGURACOES_GERAIS_RAMOSDEATIVIDADERESTRITOS_EDITAR"
E que tenha/nao tenha acesso na tela "Geral_antecipaçãoVendas"
Entao clicar no botao "Editar dados" do frame "Ramos de atividade restritos", "1"

@SETUP_ARVCONFIGURACOES_GERAIS_RAMOSDEATIVIDADERESTRITOS_VER
@RELACIONAMENTO_SUPORTE_COMERCIAL_ANALISTA @BACKOFFICE_ANALISTA_FORNECEDOR
@PLANEJA_BACKOFFICE_COBRAN_FATURA_ANALISTA @CENTRAL_DE_RELACIONAMENTO_ANALISTA
@CENTRAL_ANTECIPACAO_COORDENADOR @CENTRAL_ANTECIPACAO_ANALISTA
@GESTAO_ECONOMICA_ANALISTA @CANAIS_ALTERNATIVOS_ANALISTA @CRM_COORDENADOR
@ANTECIPACAO_DE_VENDAS_TESOURARIA_ANALISTA @ANTECIPACAO_DE_VENDAS_TESOURARIA_COORDENADOR
Cenario: CT.SEGINFO - [AUT] SETUP_ARVCONFIGURACOES_GERAIS_RAMOSDEATIVIDADERESTRITOS_VER
Dado que tenha/nao tenha o direito "SETUP_ARVCONFIGURACOES_GERAIS_RAMOSDEATIVIDADERESTRITOS_VER"
E que tenha/nao tenha acesso na tela "Geral_antecipaçãoVendas"
Entao localizar o frame "Ramos de atividade restritos", "1"

@SETUP_ARV_CUSTOS_CDI_INCLUIR
@ANTECIPACAO_DE_VENDAS_TESOURARIA_ANALISTA @ANTECIPACAO_DE_VENDAS_TESOURARIA_COORDENADOR
Cenario: CT.SEGINFO - [AUT] SETUP_ARV_CUSTOS_CDI_INCLUIR
Dado que tenha/nao tenha o direito "SETUP_ARV_CUSTOS_CDI_INCLUIR"
E que tenha/nao tenha acesso na tela "Custos"
E clicar na aba "CDI", "0"
Entao clicar no botao "Incluir", "1"

@CONFIGURACOES_ANTECIPACAOVENDAS_EXCECAORESERVAFINANCEIRA_EXPORTAR
Cenario: CT.SEGINFO - [AUT] CONFIGURACOES_ANTECIPACAOVENDAS_EXCECAORESERVAFINANCEIRA_EXPORTAR
Dado que tenha/nao tenha o direito "CONFIGURACOES_ANTECIPACAOVENDAS_EXCECAORESERVAFINANCEIRA_EXPORTAR"
E que tenha/nao tenha acesso na tela "Exceção_antecipaçãoVendas"
E o sistema exibira/nao exibira a tela "Exceção", "0"
Entao o botao "Exportar", "1" estara habilitado/desabilitado


@SETUP_ARV_CUSTOS_CUSTO_CAPTACAO_EDITAR
@ANTECIPACAO_DE_VENDAS_TESOURARIA_ANALISTA @ANTECIPACAO_DE_VENDAS_TESOURARIA_COORDENADOR
Cenario: CT.SEGINFO - [AUT] SETUP_ARV_CUSTOS_CUSTO_CAPTACAO_EDITAR
Dado que tenha/nao tenha o direito "SETUP_ARV_CUSTOS_CUSTO_CAPTACAO_EDITAR"
E que tenha/nao tenha acesso na tela "Custos"
Quando clicar na aba "CUSTO DE CAPTAÇÃO", "0"
E selecionar o botao: "incluir - custo de captacao"
E informar "29,22" no campo "previsto - incluir"
Entao clicar no botao: "confirmar - custo de captacao - incluir", "0"
Quando clicar no botao: "ok", "0"
E clicar na acao "editar - antecipação de vendas - custos", "0"
Quando informar "35,00" no campo "previsto - editar"
E clicar no botao: "confirmar - custo de captacao - editar", "0"
Entao clicar no botao: "ok - editar", "1"

@CONFIGURACOES_ANTECIPACAOVENDAS_EXCECAO_CARTAONAOPRESENTE_EDITAR
Cenario: CT.SEGINFO - [AUT] CONFIGURACOES_ANTECIPACAOVENDAS_EXCECAO_CARTAONAOPRESENTE_EDITAR
Dado que tenha/nao tenha o direito "CONFIGURACOES_ANTECIPACAOVENDAS_EXCECAO_CARTAONAOPRESENTE_EDITAR"
E que tenha/nao tenha acesso na tela "Exceção_antecipaçãoVendas"
Quando clicar na aba "Cartão não presente", "0"
Entao o link "Incluir", "0" deve estar habilitado/desabilitado
E clicar no link acao "INCLUIR", "0"
Quando clicar selecionar a opcao "Individualmente", "0"
E informar "1007595105" no campo "numero do cliente - excecao"
Quando clicar no botao "OK", "0"
Entao clicar no botao "Confirmar", "1"

@CONFIGURACOES_ANTECIPACAOVENDAS_PRECIFICACAO_CONSULTAGERAL_EDITAR
Cenario: CT.SEGINFO - [AUT] CONFIGURACOES_ANTECIPACAOVENDAS_PRECIFICACAO_CONSULTAGERAL_EDITAR
Dado que tenha/nao tenha o direito "CONFIGURACOES_ANTECIPACAOVENDAS_PRECIFICACAO_CONSULTAGERAL_EDITAR"
E que tenha/nao tenha acesso na tela "Precificação_antecipaçãoVendas"
E que tenha/nao tenha acesso na tela "Consulta geral"
Entao o botao "Editar", "1" devera estar habilitado/desabilitado

@CONFIGURACOES_ANTECIPACAOVENDAS_CONFIGURACOES_GERAIS_VER
@RELACIONAMENTO_SUPORTE_COMERCIAL_ANALISTA @PLANEJA_BACKOFFICE_COBRAN_FATURA_ANALISTA
@CENTRAL_DE_RELACIONAMENTO_ANALISTA @CENTRAL_ANTECIPACAO_COORDENADOR @CENTRAL_ANTECIPACAO_ANALISTA
@CANAIS_ALTERNATIVOS_ANALISTA @CRM_COORDENADOR @ANTECIPACAO_DE_VENDAS_TESOURARIA_ANALISTA
@ANTECIPACAO_DE_VENDAS_TESOURARIA_COORDENADOR
Cenario: CT.SEGINFO - [AUT] CONFIGURACOES_ANTECIPACAOVENDAS_CONFIGURACOES_GERAIS_VER
Dado que tenha/nao tenha o direito "CONFIGURACOES_ANTECIPACAOVENDAS_CONFIGURACOES_GERAIS_VER"
E que tenha/nao tenha acesso na tela "Geral_antecipaçãoVendas"
Entao o sistema exibira/nao exibira a tela "Antecipação de Vendas - Configurações Gerais", "1"

@CONFIGURACOES_ANTECIPACAOVENDAS_CONFGERAIS_CARTAONAOPRESENTE_VER
Cenario: CT.SEGINFO - [AUT] CONFIGURACOES_ANTECIPACAOVENDAS_CONFGERAIS_CARTAONAOPRESENTE_VER
Dado que tenha/nao tenha o direito "CONFIGURACOES_ANTECIPACAOVENDAS_CONFGERAIS_CARTAONAOPRESENTE_VER"
E que tenha/nao tenha acesso na tela "Geral_antecipaçãoVendas"
Entao localizar o frame "Cartão não presente", "1"

@CONFIGURACOES_ANTECIPACAOVENDAS_CONFGERAIS_CARTAONAOPRESENTE_EDITAR
Cenario: CT.SEGINFO - [AUT] CONFIGURACOES_ANTECIPACAOVENDAS_CONFGERAIS_CARTAONAOPRESENTE_EDITAR
Dado que tenha/nao tenha o direito "CONFIGURACOES_ANTECIPACAOVENDAS_CONFGERAIS_CARTAONAOPRESENTE_EDITAR"
E que tenha/nao tenha acesso na tela "Geral_antecipaçãoVendas"
Entao clicar no botao "Editar dados" do frame "Cartão não presente", "1"

@CONFIGURACOES_ANTECIPACAOVENDAS_EXCECAORESERVAFINANCEIRA_VER
Cenario: CT.SEGINFO - [AUT] CONFIGURACOES_ANTECIPACAOVENDAS_EXCECAORESERVAFINANCEIRA_VER
Dado que tenha/nao tenha o direito "CONFIGURACOES_ANTECIPACAOVENDAS_EXCECAORESERVAFINANCEIRA_VER"
E que tenha/nao tenha acesso na tela "Exceção_antecipaçãoVendas"
Entao o sistema exibira/nao exibira a tela "Exceção", "1"

@CONFIGURACOES_ANTECIPACAOVENDAS_GERAL_ANTECIPACAOPROGRAMADA_EDITAR
@CENTRAL_DE_RELACIONAMENTO_ANALISTA @CRM_COORDENADOR
Cenario: CT.SEGINFO - [AUT] CONFIGURACOES_ANTECIPACAOVENDAS_GERAL_ANTECIPACAOPROGRAMADA_EDITAR
Dado que tenha/nao tenha o direito "CONFIGURACOES_ANTECIPACAOVENDAS_GERAL_ANTECIPACAOPROGRAMADA_EDITAR"
E que tenha/nao tenha acesso na tela "Geral_antecipaçãoVendas"
Entao clicar no botao "Editar dados" do frame "Antecipação programada", "1"

@CONFIGURACOES_ANTECIPACAOVENDAS_GERAL_ANTECIPACAOPROGRAMADA_VER
@RELACIONAMENTO_SUPORTE_COMERCIAL_ANALISTA @BACKOFFICE_ANALISTA_FORNECEDOR
@PLANEJA_BACKOFFICE_COBRAN_FATURA_ANALISTA @CENTRAL_DE_RELACIONAMENTO_ANALISTA
@CENTRAL_ANTECIPACAO_COORDENADOR @CENTRAL_ANTECIPACAO_ANALISTA @GESTAO_ECONOMICA_ANALISTA
@CANAIS_ALTERNATIVOS_ANALISTA @CRM_COORDENADOR
Cenario: CT.SEGINFO - [AUT] CONFIGURACOES_ANTECIPACAOVENDAS_GERAL_ANTECIPACAOPROGRAMADA_VER
Dado que tenha/nao tenha o direito "CONFIGURACOES_ANTECIPACAOVENDAS_GERAL_ANTECIPACAOPROGRAMADA_VER"
E que tenha/nao tenha acesso na tela "Geral_antecipaçãoVendas"
Entao localizar o frame "Antecipação programada", "1"

@SETUP_ARVCONFIGURACOES_GERAIS_VALORMINIMOPOROPERACAOEMCADACANAL_EDITAR
Cenario: CT.SEGINFO - [AUT] SETUP_ARVCONFIGURACOES_GERAIS_VALORMINIMOPOROPERACAOEMCADACANAL_EDITAR
Dado que tenha/nao tenha o direito "SETUP_ARVCONFIGURACOES_GERAIS_VALORMINIMOPOROPERACAOEMCADACANAL_EDITAR"
E que tenha/nao tenha acesso na tela "Geral_antecipaçãoVendas"
E clicar no botao "Editar dados" do frame "Valor mínimo por operação", "0"
Entao o botao "Salvar", "1" estara habilitado/desabilitado

@SETUP_ARVCONFIGURACOES_GERAIS_VALORMINIMOPOROPERACAOEMCADACANAL_VER
@RELACIONAMENTO_SUPORTE_COMERCIAL_ANALISTA @CENTRAL_DE_RELACIONAMENTO_ANALISTA @CENTRAL_ANTECIPACAO_COORDENADOR
@CENTRAL_ANTECIPACAO_ANALISTA @GESTAO_ECONOMICA_ANALISTA @CANAIS_ALTERNATIVOS_ANALISTA @CRM_COORDENADOR
Cenario: CT.SEGINFO - [AUT] SETUP_ARVCONFIGURACOES_GERAIS_VALORMINIMOPOROPERACAOEMCADACANAL_VER
Dado que tenha/nao tenha o direito "SETUP_ARVCONFIGURACOES_GERAIS_VALORMINIMOPOROPERACAOEMCADACANAL_VER"
E que tenha/nao tenha acesso na tela "Geral_antecipaçãoVendas"
Entao clicar no botao "Editar dados" do frame "Valor mínimo por operação", "1"

@SETUP_ARV_CUSTOS_PROARV_TARIFA_LIQUIDACAO_VER
@GESTAO_ECONOMICA_ANALISTA @ANTECIPACAO_DE_VENDAS_TESOURARIA_ANALISTA
@ANTECIPACAO_DE_VENDAS_TESOURARIA_COORDENADOR
Cenario: CT.SEGINFO - [AUT] SETUP_ARV_CUSTOS_PROARV_TARIFA_LIQUIDACAO_VER
Dado que tenha/nao tenha o direito "SETUP_ARV_CUSTOS_PROARV_TARIFA_LIQUIDACAO_VER"
E que tenha/nao tenha acesso na tela "Pró-antecipação de vendas"
Quando clicar na aba "Tarifa de liquidação", "0"
Entao o botao "Pesquisar", "1" estara habilitado/desabilitado

@SETUP_ARV_CUSTOS_PROARV_TARIFA_LIQUIDACAO_EDITAR
@ANTECIPACAO_DE_VENDAS_TESOURARIA_ANALISTA @ANTECIPACAO_DE_VENDAS_TESOURARIA_COORDENADOR
Cenario: CT.SEGINFO - [AUT] SETUP_ARV_CUSTOS_PROARV_TARIFA_LIQUIDACAO_EDITAR
Dado que tenha/nao tenha o direito "SETUP_ARV_CUSTOS_PROARV_TARIFA_LIQUIDACAO_EDITAR"
E que tenha/nao tenha acesso na tela "Pró-antecipação de vendas"
Quando clicar na aba "Tarifa de liquidação", "0"
E o botao "Pesquisar", "0" estara habilitado/desabilitado
E clicar no botao "Editar", "0"
Entao o botao "Salvar", "1" estara habilitado/desabilitado

@SETUP_ARV_CUSTOS_CUSTO_OPERACIONAL_EDITAR
Cenario: CT.SEGINFO - [AUT] SETUP_ARV_CUSTOS_CUSTO_OPERACIONAL_EDITAR
Dado que tenha/nao tenha o direito "SETUP_ARV_CUSTOS_CUSTO_OPERACIONAL_EDITAR"
E que tenha/nao tenha acesso na tela "Custos"
Quando clicar na aba "CUSTO OPERACIONAL", "0"
E selecionar o botao "Incluir"
E informar "29,22" no campo "mesa-custo-operacional"
Entao clicar no botao "Confirmar", "0"
Quando clicar no botao "ok", "0"
E clicar na acao "editar - CUSTO OPERACIONAL - custos", "0"
Quando informar "35,00" no campo "mesa-custo-operacional"
E clicar no botao "Confirmar", "1"

@CONFIGURACOES_AQUISICAORECEBIVEIS_EXCECAO_ANTECIPPRAZOFLEXIVEL_VER
Cenario: CT.SEGINFO - [AUT] CONFIGURACOES_AQUISICAORECEBIVEIS_EXCECAO_ANTECIPPRAZOFLEXIVEL_VER
Dado que tenha/nao tenha o direito "CONFIGURACOES_AQUISICAORECEBIVEIS_EXCECAO_ANTECIPPRAZOFLEXIVEL_VER"
E que tenha/nao tenha acesso na tela "Exceção_antecipaçãoVendas"
Entao o sistema exibira/nao exibira a tela "Exceção", "0"
Quando clicar na aba "Antecipação de Prazo Flexível", "0"

@CONFIGURACOES_AQUISICAORECEBIVEIS_EXCECAO_ANTECIPPRAZOFLEXIVEL_EDITAR
Cenario: CT.SEGINFO - [AUT] CONFIGURACOES_AQUISICAORECEBIVEIS_EXCECAO_ANTECIPPRAZOFLEXIVEL_EDITAR
Dado que tenha/nao tenha o direito "CONFIGURACOES_AQUISICAORECEBIVEIS_EXCECAO_ANTECIPPRAZOFLEXIVEL_EDITAR"
E que tenha/nao tenha acesso na tela "Exceção_antecipaçãoVendas"
Quando clicar na aba "Antecipação de Prazo Flexível", "0"
E clicar na aba "Incluir_PrazoFlexivel", "0"
Entao podera/nao podera acessar a aba "Incluir_PrazoFlexivel"

@SETUP_ARV_CUSTOS_PROARV_PARAMETROS_VER
@ANTECIPACAO_DE_VENDAS_TESOURARIA_ANALISTA @ANTECIPACAO_DE_VENDAS_TESOURARIA_COORDENADOR
Cenario: CT.SEGINFO - [AUT] SETUP_ARV_CUSTOS_PROARV_PARAMETROS_VER
Dado que tenha/nao tenha o direito "SETUP_ARV_CUSTOS_PROARV_PARAMETROS_VER"
E que tenha/nao tenha acesso na tela "Pró-antecipação de vendas"
Quando clicar na aba "Parametros - PRO ANTECIPACAO DE VENDAS", "0"
Entao localizar o frame "Parâmetros", "1"

@SETUP_ARV_CUSTOS_PROARV_PARAMETROS_EDITAR
@ANTECIPACAO_DE_VENDAS_TESOURARIA_ANALISTA @ANTECIPACAO_DE_VENDAS_TESOURARIA_COORDENADOR
Cenario: CT.SEGINFO - [AUT] SETUP_ARV_CUSTOS_PROARV_PARAMETROS_EDITAR
Dado que tenha/nao tenha o direito "SETUP_ARV_CUSTOS_PROARV_PARAMETROS_EDITAR"
E que tenha/nao tenha acesso na tela "Pró-antecipação de vendas"
Quando clicar na aba "Parametros - PRO ANTECIPACAO DE VENDAS", "0"
E clicar na acao "Editar - PRO ANTECIPACAO DE VENDAS", "0"
Entao o botao "Confirmar", "1" estara habilitado/desabilitado

@CONFIGURACOES_ANTECIPACAOVENDAS_EXCECAORESERVAFINANCEIRA_EDITAR
Cenario: CT.SEGINFO - [AUT] CONFIGURACOES_ANTECIPACAOVENDAS_EXCECAORESERVAFINANCEIRA_EDITAR
Dado que tenha/nao tenha o direito "CONFIGURACOES_ANTECIPACAOVENDAS_EXCECAORESERVAFINANCEIRA_EDITAR"
E que tenha/nao tenha acesso na tela "Exceção_antecipaçãoVendas"
Quando clicar na aba "Incluir", "0"
Entao podera/nao podera acessar a aba "Incluir"

@CONFIGURACOES_ANTECIPACAOVENDAS_PRECIFICACAO_PRECOESPECIAL_EXPORTAR @R4
Cenario: CT.SEGINFO - [AUT] CONFIGURACOES_ANTECIPACAOVENDAS_PRECIFICACAO_PRECOESPECIAL_EXPORTAR
Dado que tenha/nao tenha o direito "CONFIGURACOES_ANTECIPACAOVENDAS_PRECIFICACAO_PRECOESPECIAL_EXPORTAR"
E que tenha/nao tenha acesso na tela "Precificação_antecipaçãoVendas"
Quando clicar na aba "Preço Especial", "0"
Entao o botao "Exportar", "1" estara habilitado/desabilitado

@CONFIGURACOES_ANTECIPACAOVENDAS_CONFGERAIS_FIDC_VER @R4
Cenario: CT.SEGINFO - [AUT] CONFIGURACOES_ANTECIPACAOVENDAS_CONFGERAIS_FIDC_VER
Dado que tenha/nao tenha o direito "CONFIGURACOES_ANTECIPACAOVENDAS_CONFGERAIS_FIDC_VER"
E que tenha/nao tenha acesso na tela "Geral_antecipaçãoVendas"
Entao localizar o frame "Taxa efetiva máxima", "1"

@CONFIGURACOES_ANTECIPACAOVENDAS_CONFGERAIS_FIDC_EDITAR @R4
Cenario: CT.SEGINFO - [AUT] CONFIGURACOES_ANTECIPACAOVENDAS_CONFGERAIS_FIDC_EDITAR
Dado que tenha/nao tenha o direito "CONFIGURACOES_ANTECIPACAOVENDAS_CONFGERAIS_FIDC_EDITAR"
E que tenha/nao tenha acesso na tela "Geral_antecipaçãoVendas"
E clicar no botao "Editar dados" do frame "FIDC", "0"
Entao o botao "Salvar", "1" estara habilitado/desabilitado
