source 'http://rubygems.org'

gem 'cucumber', '2.4.0'
gem 'watir-webdriver', '0.9.3'
gem 'test-unit', '3.1.5'
gem 'spreadsheet', '1.1.3'
gem 'magic_encoding', '0.0.2'
gem 'rspec', '3.5.0'
gem 'page-object', '1.2.0'
gem 'syntax'
gem 'nokogiri', '1.6.8.1'
gem 'rest-client', '2.0.0' 
