#language: pt
#encoding: utf-8

@ALL @OPERACOES_VAN
Funcionalidade: Validar os direitos na tela Operacoes > Van

Contexto:
Dado que eu faca login
E informe o EC "1018242187"

@OPERACOES_VAN_HABILITACAODESABILITACAO_VER
@RELACIONAMENTO_SUPORTE_COMERCIAL_ANALISTA @CADASTRO_ANALISTA_CIELO @CADASTRO_ANALISTA_CIELO_APROVADOR
@CENTRAL_HELP_DESK_ANALISTA @LOGISTICA_DE_ATENDIMENTO_A_CLIENTES_ANALISTA @BACKOFFICE_ANALISTA_FORNECEDOR
@PLANEJA_BACKOFFICE_COBRAN_FATURA_ANALISTA @CHARGEBACK_ANALISTA_INTERCAMBIO @CENTRAL_DE_RELACIONAMENTO_ANALISTA
@CENTRAL_ANTECIPACAO_COORDENADOR @CENTRAL_ANTECIPACAO_ANALISTA @GESTAO_ECONOMICA_ANALISTA
@CRM_COORDENADOR @ANTECIPACAO_DE_VENDAS_TESOURARIA_ANALISTA @ANTECIPACAO_DE_VENDAS_TESOURARIA_COORDENADOR
Cenario: Validar direito OPERACOES_VAN_HABILITACAODESABILITACAO_VER
Dado que tenha/nao tenha o direito "OPERACOES_VAN_HABILITACAODESABILITACAO_VER"
E que tenha/nao tenha acesso na tela "Habilitação e desabilitação"
Quando selecionar o combobox "Bandeira" e a opcao "AMEX"
Entao clicar no botao "Pesquisar"
