#language: pt

@ALL @OPERACOES_HIERARQUIA
Funcionalidade: Validar os direitos na tela Operacoes > Hierarquia > Grupo de pagamento

Contexto:
Dado que eu faca login

@OPERACOES_HIERARQUIA_GRUPODEPAGAMENTO_VER
@RELACIONAMENTO_SUPORTE_COMERCIAL_ANALISTA @CADASTRO_ANALISTA_CIELO @CADASTRO_ANALISTA_CIELO_APROVADOR
@LOGISTICA_DE_ATENDIMENTO_A_CLIENTES_ANALISTA @BACKOFFICE_ANALISTA_FORNECEDOR @PLANEJA_BACKOFFICE_COBRAN_FATURA_ANALISTA
@TESOURARIA_E_CONTAS_A_PAGAR_ANALISTA @CHARGEBACK_ANALISTA_INTERCAMBIO @CENTRAL_DE_RELACIONAMENTO_ANALISTA
@CENTRAL_ANTECIPACAO_COORDENADOR @CENTRAL_ANTECIPACAO_ANALISTA @GESTAO_ECONOMICA_ANALISTA
@CANAIS_ALTERNATIVOS_ANALISTA @JURIDICO_CONTENCIOSO_ANALISTA @CRM_COORDENADOR
@ANTECIPACAO_DE_VENDAS_TESOURARIA_ANALISTA @ANTECIPACAO_DE_VENDAS_TESOURARIA_COORDENADOR
Cenario: Validar direito OPERACOES_HIERARQUIA_GRUPODEPAGAMENTO_VER
Dado que tenha/nao tenha o direito "OPERACOES_HIERARQUIA_GRUPODEPAGAMENTO_VER"
E que tenha/nao tenha acesso na tela "Grupo de pagamento"
Quando clicar na aba "PESQUISAR"
E selecionar a opcao "Nº do cliente individual" do campo "Pesquisar grupo por"
E informar "1007595105" no campo "numero do cliente individual"
Entao clicar no botao "Pesquisar"

@OPERACOES_HIERARQUIA_GRUPODEPAGAMENTO_EDITAR
Cenario: Validar direito OPERACOES_HIERARQUIA_GRUPODEPAGAMENTO_EDITAR
Dado que tenha/nao tenha o direito "OPERACOES_HIERARQUIA_GRUPODEPAGAMENTO_EDITAR"
E que tenha/nao tenha acesso na tela "Grupo de pagamento"
Quando informar "1007595105" no campo "numero do cliente individual"
E clicar no botao "Pesquisar"
E clicar no link "1007595105"
Entao o botao "Editar Dados" estara habilitado/desabilitado
