#language: pt

@ALL @CLIENTES_CADASTRO_HISTORICO
Funcionalidade: Validar os direitos na tela Cliente > Cadastro > Informacoes do cliente > Historico

Contexto:
Dado que eu faca login
E informe o EC "1018242187"

@CLIENTES_HISTORICOALTERACOES_CADASTROCLIENTE_VER
@RELACIONAMENTO_SUPORTE_COMERCIAL_ANALISTA @CADASTRO_ANALISTA_CIELO @CADASTRO_ANALISTA_CIELO_APROVADOR
@CENTRAL_HELP_DESK_ANALISTA @LOGISTICA_DE_ATENDIMENTO_A_CLIENTES_ANALISTA @BACKOFFICE_ANALISTA_FORNECEDOR
@PLANEJA_BACKOFFICE_COBRAN_FATURA_ANALISTA @CHARGEBACK_ANALISTA_INTERCAMBIO @CENTRAL_DE_RELACIONAMENTO_ANALISTA
@CENTRAL_ANTECIPACAO_COORDENADOR @CENTRAL_ANTECIPACAO_ANALISTA @GESTAO_ECONOMICA_ANALISTA
@CANAIS_ALTERNATIVOS_ANALISTA @CRM_COORDENADOR @ANTECIPACAO_DE_VENDAS_TESOURARIA_ANALISTA
@ANTECIPACAO_DE_VENDAS_TESOURARIA_COORDENADOR
Cenario: CT.SEGINFO - [AUT] CLIENTES_HISTORICOALTERACOES_CADASTROCLIENTE_VER
Dado que tenha/nao tenha o direito "CLIENTES_HISTORICOALTERACOES_CADASTROCLIENTE_VER"
E que tenha/nao tenha acesso na tela "Informações do cliente"
Quando clicar na aba "Histórico"
Entao podera/nao podera acessar a aba "Histórico"
