#language: pt

@ALL @CLIENTE_DEMANDAS
Funcionalidade: Validar os direitos na tela Cliente > Demanda > Abertura de Demanda

Contexto:
Dado que eu faca login
E informe o EC "1018242187"

@CLIENTE_DEMANDAS_ABERTURADEMANDA_VER
@RELACIONAMENTO_SUPORTE_COMERCIAL_ANALISTA @CADASTRO_ANALISTA_CIELO @CADASTRO_ANALISTA_CIELO_APROVADOR
@CENTRAL_HELP_DESK_ANALISTA @LOGISTICA_DE_ATENDIMENTO_A_CLIENTES_ANALISTA @BACKOFFICE_ANALISTA_FORNECEDOR
@PLANEJA_BACKOFFICE_COBRAN_FATURA_ANALISTA @CHARGEBACK_ANALISTA_INTERCAMBIO @CENTRAL_DE_RELACIONAMENTO_ANALISTA
@CENTRAL_ANTECIPACAO_COORDENADOR @CENTRAL_ANTECIPACAO_ANALISTA @CANAIS_ALTERNATIVOS_ANALISTA
@CRM_COORDENADOR @ANTECIPACAO_DE_VENDAS_TESOURARIA_ANALISTA @ANTECIPACAO_DE_VENDAS_TESOURARIA_COORDENADOR
Cenario: Validar direito CLIENTE_DEMANDAS_ABERTURADEMANDA_VER
Dado que tenha/nao tenha o direito "CLIENTE_DEMANDAS_ABERTURADEMANDA_VER"
E que tenha/nao tenha acesso na tela "Abertura de demanda"
Entao o sistema exibira/nao exibira a tela "Abertura de demanda"

@CLIENTE_DEMANDAS_ABERTURADEMANDA_INCLUIR
@CADASTRO_ANALISTA_CIELO @CADASTRO_ANALISTA_CIELO_APROVADOR @CENTRAL_HELP_DESK_ANALISTA
@LOGISTICA_DE_ATENDIMENTO_A_CLIENTES_ANALISTA @BACKOFFICE_ANALISTA_FORNECEDOR @PLANEJA_BACKOFFICE_COBRAN_FATURA_ANALISTA
@CHARGEBACK_ANALISTA_INTERCAMBIO @CENTRAL_DE_RELACIONAMENTO_ANALISTA @CRM_COORDENADOR
Cenario: Validar direito CLIENTE_DEMANDAS_ABERTURADEMANDA_INCLUIR
Dado que tenha/nao tenha o direito "CLIENTE_DEMANDAS_ABERTURADEMANDA_INCLUIR"
E que tenha/nao tenha acesso na tela "Abertura de demanda"
Entao o botao "Continuar" devera estar habilitado/desabilitado
