#language: pt

@ALL @CLIENTE_REGULATORIOS
Funcionalidade: Validar os direitos na tela Operacoes > Regularizações financeiras

Contexto:
Dado que eu faca login
E informe o nivel de hierarquia como "Grupo comercial"
E informe o EC "1018242187"

@CLIENTES_REGULATORIOS_DIRF_VER
@RELACIONAMENTO_SUPORTE_COMERCIAL_ANALISTA @PLANEJA_BACKOFFICE_COBRAN_FATURA_ANALISTA @CHARGEBACK_ANALISTA_INTERCAMBIO
@CENTRAL_DE_RELACIONAMENTO_ANALISTA @CENTRAL_ANTECIPACAO_COORDENADOR @CENTRAL_ANTECIPACAO_ANALISTA
@CONTABILIDADE_NEGOCIO_E_TRIBUTARIO_ANALISTA @CRM_COORDENADOR @ANTECIPACAO_DE_VENDAS_TESOURARIA_ANALISTA
@ANTECIPACAO_DE_VENDAS_TESOURARIA_COORDENADOR
Cenario: CT.SEGINFO - [AUT] CLIENTES_REGULATORIOS_DIRF_VER
Dado que tenha/nao tenha o direito "CLIENTES_REGULATORIOS_DIRF_VER"
E que tenha/nao tenha acesso na tela "DIRF"
Entao o sistema exibira/nao exibira a tela "DIRF"

@CLIENTES_REGULATORIOS_DIRF_DEMONSTRATIVO_VER
Cenario: CT.SEGINFO - [AUT] CLIENTES_REGULATORIOS_DIRF_DEMONSTRATIVO_VER
Dado que tenha/nao tenha o direito "CLIENTES_REGULATORIOS_DIRF_DEMONSTRATIVO_VER"
E que tenha/nao tenha acesso na tela "DIRF"
Quando clicar na aba "DEMONSTRATIVO", "0"
Entao podera/nao podera acessar a aba "DEMONSTRATIVO"

@CLIENTES_REGULATORIOS_DIRF_SOLICITAR
@CENTRAL_DE_RELACIONAMENTO_ANALISTA @CONTABILIDADE_NEGOCIO_E_TRIBUTARIO_ANALISTA @CRM_COORDENADOR
Cenario: CT.SEGINFO - [AUT] CLIENTES_REGULATORIOS_DIRF_SOLICITAR
Dado que tenha/nao tenha o direito "CLIENTES_REGULATORIOS_DIRF_SOLICITAR"
E que tenha/nao tenha acesso na tela "DIRF"
Quando clicar na aba "SOLICITAÇÃO DA PRÉVIA", "0"
Entao podera/nao podera acessar a aba "SOLICITAÇÃO DA PRÉVIA"
